ARG AIRFLOW_IMAGE
FROM ${AIRFLOW_IMAGE}

COPY requirements.txt /requirements.txt

USER airflow

RUN pip install --upgrade pip setuptools wheel --user \
 && pip install --user -r /requirements.txt

# USER airflow  # 이미 airflow 이므로 다시 선언 불필요
